### ISSUE TITLE
com.google.gwt.core.client.Callback cannot be resolved in GWT 2.3.0

### ISSUE THREAD

**Issue by GoogleCodeExporter** [chetsmartboy/gwt-oauth2#1]
```
What steps will reproduce the problem?
1. Download the demo
2. Setup the demo
3. Compile

Compiler says:

The type com.google.gwt.core.client.Callback cannot be resolved. It is 
indirectly referenced from required .class files    


```

Original issue reported on code.google.com by `giulio.r...@gmail.com` on 27 May 2011 at 9:27

**Comment by GoogleCodeExporter** [comment]
```
To solve temporary the problem I've downloaded the source code and added the 
Callback class to the client package.


package com.google.api.gwt.oauth2.client;

public interface Callback<T, F> {

    /**
     * Called when an asynchronous call fails to complete normally.
     * 
     * @param reason
     *            failure encountered
     */
    void onFailure(F reason);

    /**
     * Called when an asynchronous call completes successfully.
     * 
     * @param result
     *            the value returned
     */
    void onSuccess(T result);
}

```

Original comment by `giulio.r...@gmail.com` on 27 May 2011 at 1:10

**Comment by GoogleCodeExporter** [comment]
```
Callback is available if you build from GWT trunk, and is scheduled to be 
included in GWT SDK 2.4.

Since most people don't do that, I've got a change in the works to add the 
interface to the library itself, @deprecated, scheduled to be removed and 
replaced with the real Callback<T, F> when GWT 2.4 is released.

Sorry for the inconvenience.
```

Original comment by `jasonhall@google.com` on 27 May 2011 at 1:51
- Changed state: **Started**

**Comment by GoogleCodeExporter** [comment]
```
Thanks!
```

Original comment by `giulio.r...@gmail.com` on 27 May 2011 at 2:00

**Comment by GoogleCodeExporter** [comment]
```
The change has been made, and the new release has been posted: 
http://code.google.com/p/gwt-oauth2/downloads/detail?name=gwt-oauth2-0.1.1-alpha
.jar

Please take a look and let me know if you have any further problems.
```

Original comment by `jasonhall@google.com` on 27 May 2011 at 3:12
- Changed state: **Fixed**

**Comment by GoogleCodeExporter** [comment]
```
It works correctly using gwt-oauth2-0.1.1-alpha.jar. No more compilation error: 
"com.google.gwt.core.client.Callback cannot be resolved" :)

Thanks!

http://socialmkitaui.appspot.com/index.html
```

Original comment by `giulio.r...@gmail.com` on 27 May 2011 at 3:46
